# Based on https://github.com/PrakashTrove/AWS-CodeBuild-NetCore/blob/master/buildspec.yml
# AWS CodeBuild spec to build an Elastic Beanstalk artifact for AWS CodePipeline to deploy
version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  
  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore ProjectBase/ProjectBase.csproj
  
  build:
    commands:
      - echo Build started on `date`
      - dotnet build ProjectBase/ProjectBase.csproj
      - echo Test started on `date`
      - dotnet test ProjectBase/ProjectBase.csproj
  
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 -o ./build_output ProjectBase/ProjectBase.csproj
      - dotnet dev-certs https --trust
      - mkdir -p ./build_output/project_files
      - cp -R .ebextensions build_output/ # manually copy .ebextensions folder content if artifacts->files failed
      - cp -R .platform build_output/ # manually copy .platform folder content if artifacts->files failed

artifacts:
  files:
    - ./**/*
    - .ebextensions/**/*
    - .platform/**/*
  base-directory: './build_output'
